branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: udagram-image-filter-dev
  branch: master
  default_ec2_keyname: udagram-aws-eb
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: origin
  sc: git
  workspace_type: Application
